// Country list based on ISO 3166 standard codes.
// Includes ISO 3166-1 alpha-2 and alpha-3 country codes.

import type { CountryData } from "./country";

export const countries: CountryData[] = [
    {
        name: "Afghanistan",
        alpha2Code: "AF",
        alpha3Code: "AFG",
        dialingCode: 93,
        dialingCodePrimary: true,
    },
    {
        name: "Albania",
        alpha2Code: "AL",
        alpha3Code: "ALB",
        dialingCode: 355,
        dialingCodePrimary: true,
    },
    {
        name: "Algeria",
        alpha2Code: "DZ",
        alpha3Code: "DZA",
        dialingCode: 213,
        dialingCodePrimary: true,
    },
    {
        name: "Andorra",
        alpha2Code: "AD",
        alpha3Code: "AND",
        dialingCode: 376,
        dialingCodePrimary: true,
    },
    {
        name: "Angola",
        alpha2Code: "AO",
        alpha3Code: "AGO",
        dialingCode: 244,
        dialingCodePrimary: true,
    },
    {
        name: "Antigua and Barbuda",
        alpha2Code: "AG",
        alpha3Code: "ATG",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Argentina",
        alpha2Code: "AR",
        alpha3Code: "ARG",
        dialingCode: 54,
        dialingCodePrimary: true,
    },
    {
        name: "Armenia",
        alpha2Code: "AM",
        alpha3Code: "ARM",
        dialingCode: 374,
        dialingCodePrimary: true,
    },
    {
        name: "Australia",
        alpha2Code: "AU",
        alpha3Code: "AUS",
        dialingCode: 61,
        dialingCodePrimary: true,
    },
    {
        name: "Austria",
        alpha2Code: "AT",
        alpha3Code: "AUT",
        dialingCode: 43,
        dialingCodePrimary: true,
    },
    {
        name: "Azerbaijan",
        alpha2Code: "AZ",
        alpha3Code: "AZE",
        dialingCode: 994,
        dialingCodePrimary: true,
    },
    {
        name: "Bahamas",
        alpha2Code: "BS",
        alpha3Code: "BHS",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Bahrain",
        alpha2Code: "BH",
        alpha3Code: "BHR",
        dialingCode: 973,
        dialingCodePrimary: true,
    },
    {
        name: "Bangladesh",
        alpha2Code: "BD",
        alpha3Code: "BGD",
        dialingCode: 880,
        dialingCodePrimary: true,
    },
    {
        name: "Barbados",
        alpha2Code: "BB",
        alpha3Code: "BRB",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Belarus",
        alpha2Code: "BY",
        alpha3Code: "BLR",
        dialingCode: 375,
        dialingCodePrimary: true,
    },
    {
        name: "Belgium",
        alpha2Code: "BE",
        alpha3Code: "BEL",
        dialingCode: 32,
        dialingCodePrimary: true,
    },
    {
        name: "Belize",
        alpha2Code: "BZ",
        alpha3Code: "BLZ",
        dialingCode: 501,
        dialingCodePrimary: false,
    },
    {
        name: "Benin",
        alpha2Code: "BJ",
        alpha3Code: "BEN",
        dialingCode: 229,
        dialingCodePrimary: true,
    },
    {
        name: "Bhutan",
        alpha2Code: "BT",
        alpha3Code: "BTN",
        dialingCode: 975,
        dialingCodePrimary: true,
    },
    {
        name: "Bolivia",
        alpha2Code: "BO",
        alpha3Code: "BOL",
        dialingCode: 591,
        dialingCodePrimary: true,
    },
    {
        name: "Bosnia and Herzegovina",
        alpha2Code: "BA",
        alpha3Code: "BIH",
        dialingCode: 387,
        dialingCodePrimary: true,
    },
    {
        name: "Botswana",
        alpha2Code: "BW",
        alpha3Code: "BWA",
        dialingCode: 267,
        dialingCodePrimary: true,
    },
    {
        name: "Brazil",
        alpha2Code: "BR",
        alpha3Code: "BRA",
        dialingCode: 55,
        dialingCodePrimary: true,
    },
    {
        name: "Brunei",
        alpha2Code: "BN",
        alpha3Code: "BRN",
        dialingCode: 673,
        dialingCodePrimary: true,
    },
    {
        name: "Bulgaria",
        alpha2Code: "BG",
        alpha3Code: "BGR",
        dialingCode: 359,
        dialingCodePrimary: true,
    },
    {
        name: "Burkina Faso",
        alpha2Code: "BF",
        alpha3Code: "BFA",
        dialingCode: 226,
        dialingCodePrimary: true,
    },
    {
        name: "Burundi",
        alpha2Code: "BI",
        alpha3Code: "BDI",
        dialingCode: 257,
        dialingCodePrimary: true,
    },
    {
        name: "Cambodia",
        alpha2Code: "KH",
        alpha3Code: "KHM",
        dialingCode: 855,
        dialingCodePrimary: true,
    },
    {
        name: "Cameroon",
        alpha2Code: "CM",
        alpha3Code: "CMR",
        dialingCode: 237,
        dialingCodePrimary: true,
    },
    {
        name: "Canada",
        alpha2Code: "CA",
        alpha3Code: "CAN",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Cape Verde",
        alpha2Code: "CV",
        alpha3Code: "CPV",
        dialingCode: 238,
        dialingCodePrimary: true,
    },
    {
        name: "Central African Republic",
        alpha2Code: "CF",
        alpha3Code: "CAF",
        dialingCode: 236,
        dialingCodePrimary: true,
    },
    {
        name: "Chad",
        alpha2Code: "TD",
        alpha3Code: "TCD",
        dialingCode: 235,
        dialingCodePrimary: true,
    },
    {
        name: "Chile",
        alpha2Code: "CL",
        alpha3Code: "CHL",
        dialingCode: 56,
        dialingCodePrimary: true,
    },
    {
        name: "China",
        alpha2Code: "CN",
        alpha3Code: "CHN",
        dialingCode: 86,
        dialingCodePrimary: true,
    },
    {
        name: "Colombia",
        alpha2Code: "CO",
        alpha3Code: "COL",
        dialingCode: 57,
        dialingCodePrimary: true,
    },
    {
        name: "Comoros",
        alpha2Code: "KM",
        alpha3Code: "COM",
        dialingCode: 269,
        dialingCodePrimary: true,
    },
    {
        name: "Costa Rica",
        alpha2Code: "CR",
        alpha3Code: "CRI",
        dialingCode: 506,
        dialingCodePrimary: true,
    },
    {
        name: "Croatia",
        alpha2Code: "HR",
        alpha3Code: "HRV",
        dialingCode: 385,
        dialingCodePrimary: true,
    },
    {
        name: "Cuba",
        alpha2Code: "CU",
        alpha3Code: "CUB",
        dialingCode: 53,
        dialingCodePrimary: true,
    },
    {
        name: "Cyprus",
        alpha2Code: "CY",
        alpha3Code: "CYP",
        dialingCode: 357,
        dialingCodePrimary: true,
    },
    {
        name: "Czechia",
        alpha2Code: "CZ",
        alpha3Code: "CZE",
        dialingCode: 420,
        dialingCodePrimary: true,
    },
    {
        name: "Denmark",
        alpha2Code: "DK",
        alpha3Code: "DNK",
        dialingCode: 45,
        dialingCodePrimary: true,
    },
    {
        name: "Djibouti",
        alpha2Code: "DJ",
        alpha3Code: "DJI",
        dialingCode: 253,
        dialingCodePrimary: true,
    },
    {
        name: "Dominica",
        alpha2Code: "DM",
        alpha3Code: "DMA",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Dominican Republic",
        alpha2Code: "DO",
        alpha3Code: "DOM",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Ecuador",
        alpha2Code: "EC",
        alpha3Code: "ECU",
        dialingCode: 593,
        dialingCodePrimary: true,
    },
    {
        name: "Egypt",
        alpha2Code: "EG",
        alpha3Code: "EGY",
        dialingCode: 20,
        dialingCodePrimary: true,
    },
    {
        name: "El Salvador",
        alpha2Code: "SV",
        alpha3Code: "SLV",
        dialingCode: 503,
        dialingCodePrimary: true,
    },
    {
        name: "Equatorial Guinea",
        alpha2Code: "GQ",
        alpha3Code: "GNQ",
        dialingCode: 240,
        dialingCodePrimary: true,
    },
    {
        name: "Eritrea",
        alpha2Code: "ER",
        alpha3Code: "ERI",
        dialingCode: 291,
        dialingCodePrimary: true,
    },
    {
        name: "Estonia",
        alpha2Code: "EE",
        alpha3Code: "EST",
        dialingCode: 372,
        dialingCodePrimary: true,
    },
    {
        name: "Eswatini",
        alpha2Code: "SZ",
        alpha3Code: "SWZ",
        dialingCode: 268,
        dialingCodePrimary: true,
    },
    {
        name: "Ethiopia",
        alpha2Code: "ET",
        alpha3Code: "ETH",
        dialingCode: 251,
        dialingCodePrimary: true,
    },
    {
        name: "Fiji",
        alpha2Code: "FJ",
        alpha3Code: "FJI",
        dialingCode: 679,
        dialingCodePrimary: true,
    },
    {
        name: "Finland",
        alpha2Code: "FI",
        alpha3Code: "FIN",
        dialingCode: 358,
        dialingCodePrimary: true,
    },
    {
        name: "France",
        alpha2Code: "FR",
        alpha3Code: "FRA",
        dialingCode: 33,
        dialingCodePrimary: true,
    },
    {
        name: "Gabon",
        alpha2Code: "GA",
        alpha3Code: "GAB",
        dialingCode: 241,
        dialingCodePrimary: true,
    },
    {
        name: "Gambia",
        alpha2Code: "GM",
        alpha3Code: "GMB",
        dialingCode: 220,
        dialingCodePrimary: true,
    },
    {
        name: "Georgia",
        alpha2Code: "GE",
        alpha3Code: "GEO",
        dialingCode: 995,
        dialingCodePrimary: true,
    },
    {
        name: "Germany",
        alpha2Code: "DE",
        alpha3Code: "DEU",
        dialingCode: 49,
        dialingCodePrimary: true,
    },
    {
        name: "Ghana",
        alpha2Code: "GH",
        alpha3Code: "GHA",
        dialingCode: 233,
        dialingCodePrimary: true,
    },
    {
        name: "Greece",
        alpha2Code: "GR",
        alpha3Code: "GRC",
        dialingCode: 30,
        dialingCodePrimary: true,
    },
    {
        name: "Grenada",
        alpha2Code: "GD",
        alpha3Code: "GRD",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Guatemala",
        alpha2Code: "GT",
        alpha3Code: "GTM",
        dialingCode: 502,
        dialingCodePrimary: true,
    },
    {
        name: "Guinea",
        alpha2Code: "GN",
        alpha3Code: "GIN",
        dialingCode: 224,
        dialingCodePrimary: true,
    },
    {
        name: "Guinea-Bissau",
        alpha2Code: "GW",
        alpha3Code: "GNB",
        dialingCode: 245,
        dialingCodePrimary: true,
    },
    {
        name: "Guyana",
        alpha2Code: "GY",
        alpha3Code: "GUY",
        dialingCode: 592,
        dialingCodePrimary: true,
    },
    {
        name: "Haiti",
        alpha2Code: "HT",
        alpha3Code: "HTI",
        dialingCode: 509,
        dialingCodePrimary: true,
    },
    {
        name: "Honduras",
        alpha2Code: "HN",
        alpha3Code: "HND",
        dialingCode: 504,
        dialingCodePrimary: true,
    },
    {
        name: "Hungary",
        alpha2Code: "HU",
        alpha3Code: "HUN",
        dialingCode: 36,
        dialingCodePrimary: true,
    },
    {
        name: "Iceland",
        alpha2Code: "IS",
        alpha3Code: "ISL",
        dialingCode: 354,
        dialingCodePrimary: true,
    },
    {
        name: "India",
        alpha2Code: "IN",
        alpha3Code: "IND",
        dialingCode: 91,
        dialingCodePrimary: true,
    },
    {
        name: "Indonesia",
        alpha2Code: "ID",
        alpha3Code: "IDN",
        dialingCode: 62,
        dialingCodePrimary: true,
    },
    {
        name: "Iran",
        alpha2Code: "IR",
        alpha3Code: "IRN",
        dialingCode: 98,
        dialingCodePrimary: true,
    },
    {
        name: "Iraq",
        alpha2Code: "IQ",
        alpha3Code: "IRQ",
        dialingCode: 964,
        dialingCodePrimary: true,
    },
    {
        name: "Ireland",
        alpha2Code: "IE",
        alpha3Code: "IRL",
        dialingCode: 353,
        dialingCodePrimary: true,
    },
    {
        name: "Italy",
        alpha2Code: "IT",
        alpha3Code: "ITA",
        dialingCode: 39,
        dialingCodePrimary: true,
    },
    {
        name: "Jamaica",
        alpha2Code: "JM",
        alpha3Code: "JAM",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Japan",
        alpha2Code: "JP",
        alpha3Code: "JPN",
        dialingCode: 81,
        dialingCodePrimary: true,
    },
    {
        name: "Jordan",
        alpha2Code: "JO",
        alpha3Code: "JOR",
        dialingCode: 962,
        dialingCodePrimary: true,
    },
    {
        name: "Kazakhstan",
        alpha2Code: "KZ",
        alpha3Code: "KAZ",
        dialingCode: 7,
        dialingCodePrimary: false,
    },
    {
        name: "Kenya",
        alpha2Code: "KE",
        alpha3Code: "KEN",
        dialingCode: 254,
        dialingCodePrimary: true,
    },
    {
        name: "Kiribati",
        alpha2Code: "KI",
        alpha3Code: "KIR",
        dialingCode: 686,
        dialingCodePrimary: true,
    },
    {
        name: "Kuwait",
        alpha2Code: "KW",
        alpha3Code: "KWT",
        dialingCode: 965,
        dialingCodePrimary: true,
    },
    {
        name: "Kyrgyzstan",
        alpha2Code: "KG",
        alpha3Code: "KGZ",
        dialingCode: 996,
        dialingCodePrimary: true,
    },
    {
        name: "Laos",
        alpha2Code: "LA",
        alpha3Code: "LAO",
        dialingCode: 856,
        dialingCodePrimary: true,
    },
    {
        name: "Latvia",
        alpha2Code: "LV",
        alpha3Code: "LVA",
        dialingCode: 371,
        dialingCodePrimary: true,
    },
    {
        name: "Lebanon",
        alpha2Code: "LB",
        alpha3Code: "LBN",
        dialingCode: 961,
        dialingCodePrimary: true,
    },
    {
        name: "Lesotho",
        alpha2Code: "LS",
        alpha3Code: "LSO",
        dialingCode: 266,
        dialingCodePrimary: true,
    },
    {
        name: "Liberia",
        alpha2Code: "LR",
        alpha3Code: "LBR",
        dialingCode: 231,
        dialingCodePrimary: true,
    },
    {
        name: "Libya",
        alpha2Code: "LY",
        alpha3Code: "LBY",
        dialingCode: 218,
        dialingCodePrimary: true,
    },
    {
        name: "Liechtenstein",
        alpha2Code: "LI",
        alpha3Code: "LIE",
        dialingCode: 423,
        dialingCodePrimary: true,
    },
    {
        name: "Lithuania",
        alpha2Code: "LT",
        alpha3Code: "LTU",
        dialingCode: 370,
        dialingCodePrimary: true,
    },
    {
        name: "Luxembourg",
        alpha2Code: "LU",
        alpha3Code: "LUX",
        dialingCode: 352,
        dialingCodePrimary: true,
    },
    {
        name: "Madagascar",
        alpha2Code: "MG",
        alpha3Code: "MDG",
        dialingCode: 261,
        dialingCodePrimary: true,
    },
    {
        name: "Malawi",
        alpha2Code: "MW",
        alpha3Code: "MWI",
        dialingCode: 265,
        dialingCodePrimary: true,
    },
    {
        name: "Malaysia",
        alpha2Code: "MY",
        alpha3Code: "MYS",
        dialingCode: 60,
        dialingCodePrimary: true,
    },
    {
        name: "Maldives",
        alpha2Code: "MV",
        alpha3Code: "MDV",
        dialingCode: 960,
        dialingCodePrimary: true,
    },
    {
        name: "Mali",
        alpha2Code: "ML",
        alpha3Code: "MLI",
        dialingCode: 223,
        dialingCodePrimary: true,
    },
    {
        name: "Malta",
        alpha2Code: "MT",
        alpha3Code: "MLT",
        dialingCode: 356,
        dialingCodePrimary: true,
    },
    {
        name: "Marshall Islands",
        alpha2Code: "MH",
        alpha3Code: "MHL",
        dialingCode: 692,
        dialingCodePrimary: true,
    },
    {
        name: "Mauritania",
        alpha2Code: "MR",
        alpha3Code: "MRT",
        dialingCode: 222,
        dialingCodePrimary: true,
    },
    {
        name: "Mauritius",
        alpha2Code: "MU",
        alpha3Code: "MUS",
        dialingCode: 230,
        dialingCodePrimary: true,
    },
    {
        name: "Mexico",
        alpha2Code: "MX",
        alpha3Code: "MEX",
        dialingCode: 52,
        dialingCodePrimary: true,
    },
    {
        name: "Micronesia",
        alpha2Code: "FM",
        alpha3Code: "FSM",
        dialingCode: 691,
        dialingCodePrimary: true,
    },
    {
        name: "Moldova",
        alpha2Code: "MD",
        alpha3Code: "MDA",
        dialingCode: 373,
        dialingCodePrimary: true,
    },
    {
        name: "Monaco",
        alpha2Code: "MC",
        alpha3Code: "MCO",
        dialingCode: 377,
        dialingCodePrimary: true,
    },
    {
        name: "Mongolia",
        alpha2Code: "MN",
        alpha3Code: "MNG",
        dialingCode: 976,
        dialingCodePrimary: true,
    },
    {
        name: "Montenegro",
        alpha2Code: "ME",
        alpha3Code: "MNE",
        dialingCode: 382,
        dialingCodePrimary: true,
    },
    {
        name: "Morocco",
        alpha2Code: "MA",
        alpha3Code: "MAR",
        dialingCode: 212,
        dialingCodePrimary: true,
    },
    {
        name: "Mozambique",
        alpha2Code: "MZ",
        alpha3Code: "MOZ",
        dialingCode: 258,
        dialingCodePrimary: true,
    },
    {
        name: "Namibia",
        alpha2Code: "NA",
        alpha3Code: "NAM",
        dialingCode: 264,
        dialingCodePrimary: true,
    },
    {
        name: "Nauru",
        alpha2Code: "NR",
        alpha3Code: "NRU",
        dialingCode: 674,
        dialingCodePrimary: true,
    },
    {
        name: "Nepal",
        alpha2Code: "NP",
        alpha3Code: "NPL",
        dialingCode: 977,
        dialingCodePrimary: true,
    },
    {
        name: "Netherlands",
        alpha2Code: "NL",
        alpha3Code: "NLD",
        dialingCode: 31,
        dialingCodePrimary: true,
    },
    {
        name: "New Zealand",
        alpha2Code: "NZ",
        alpha3Code: "NZL",
        dialingCode: 64,
        dialingCodePrimary: true,
    },
    {
        name: "Nicaragua",
        alpha2Code: "NI",
        alpha3Code: "NIC",
        dialingCode: 505,
        dialingCodePrimary: true,
    },
    {
        name: "Niger",
        alpha2Code: "NE",
        alpha3Code: "NER",
        dialingCode: 227,
        dialingCodePrimary: true,
    },
    {
        name: "Nigeria",
        alpha2Code: "NG",
        alpha3Code: "NGA",
        dialingCode: 234,
        dialingCodePrimary: true,
    },
    {
        name: "North Korea",
        alpha2Code: "KP",
        alpha3Code: "PRK",
        dialingCode: 850,
        dialingCodePrimary: true,
    },
    {
        name: "North Macedonia",
        alpha2Code: "MK",
        alpha3Code: "MKD",
        dialingCode: 389,
        dialingCodePrimary: true,
    },
    {
        name: "Norway",
        alpha2Code: "NO",
        alpha3Code: "NOR",
        dialingCode: 47,
        dialingCodePrimary: true,
    },
    {
        name: "Oman",
        alpha2Code: "OM",
        alpha3Code: "OMN",
        dialingCode: 968,
        dialingCodePrimary: true,
    },
    {
        name: "Pakistan",
        alpha2Code: "PK",
        alpha3Code: "PAK",
        dialingCode: 92,
        dialingCodePrimary: true,
    },
    {
        name: "Palau",
        alpha2Code: "PW",
        alpha3Code: "PLW",
        dialingCode: 680,
        dialingCodePrimary: true,
    },
    {
        name: "Panama",
        alpha2Code: "PA",
        alpha3Code: "PAN",
        dialingCode: 507,
        dialingCodePrimary: true,
    },
    {
        name: "Papua New Guinea",
        alpha2Code: "PG",
        alpha3Code: "PNG",
        dialingCode: 675,
        dialingCodePrimary: true,
    },
    {
        name: "Paraguay",
        alpha2Code: "PY",
        alpha3Code: "PRY",
        dialingCode: 595,
        dialingCodePrimary: true,
    },
    {
        name: "Peru",
        alpha2Code: "PE",
        alpha3Code: "PER",
        dialingCode: 51,
        dialingCodePrimary: true,
    },
    {
        name: "Philippines",
        alpha2Code: "PH",
        alpha3Code: "PHL",
        dialingCode: 63,
        dialingCodePrimary: true,
    },
    {
        name: "Poland",
        alpha2Code: "PL",
        alpha3Code: "POL",
        dialingCode: 48,
        dialingCodePrimary: true,
    },
    {
        name: "Portugal",
        alpha2Code: "PT",
        alpha3Code: "PRT",
        dialingCode: 351,
        dialingCodePrimary: true,
    },
    {
        name: "Qatar",
        alpha2Code: "QA",
        alpha3Code: "QAT",
        dialingCode: 974,
        dialingCodePrimary: true,
    },
    {
        name: "Romania",
        alpha2Code: "RO",
        alpha3Code: "ROU",
        dialingCode: 40,
        dialingCodePrimary: true,
    },
    {
        name: "Russia",
        alpha2Code: "RU",
        alpha3Code: "RUS",
        dialingCode: 7,
        dialingCodePrimary: true,
    },
    {
        name: "Rwanda",
        alpha2Code: "RW",
        alpha3Code: "RWA",
        dialingCode: 250,
        dialingCodePrimary: true,
    },
    {
        name: "Saudi Arabia",
        alpha2Code: "SA",
        alpha3Code: "SAU",
        dialingCode: 966,
        dialingCodePrimary: true,
    },
    {
        name: "Senegal",
        alpha2Code: "SN",
        alpha3Code: "SEN",
        dialingCode: 221,
        dialingCodePrimary: true,
    },
    {
        name: "Serbia",
        alpha2Code: "RS",
        alpha3Code: "SRB",
        dialingCode: 381,
        dialingCodePrimary: true,
    },
    {
        name: "Seychelles",
        alpha2Code: "SC",
        alpha3Code: "SYC",
        dialingCode: 248,
        dialingCodePrimary: true,
    },
    {
        name: "Sierra Leone",
        alpha2Code: "SL",
        alpha3Code: "SLE",
        dialingCode: 232,
        dialingCodePrimary: true,
    },
    {
        name: "Singapore",
        alpha2Code: "SG",
        alpha3Code: "SGP",
        dialingCode: 65,
        dialingCodePrimary: true,
    },
    {
        name: "Slovakia",
        alpha2Code: "SK",
        alpha3Code: "SVK",
        dialingCode: 421,
        dialingCodePrimary: true,
    },
    {
        name: "Slovenia",
        alpha2Code: "SI",
        alpha3Code: "SVN",
        dialingCode: 386,
        dialingCodePrimary: true,
    },
    {
        name: "Solomon Islands",
        alpha2Code: "SB",
        alpha3Code: "SLB",
        dialingCode: 677,
        dialingCodePrimary: true,
    },
    {
        name: "Somalia",
        alpha2Code: "SO",
        alpha3Code: "SOM",
        dialingCode: 252,
        dialingCodePrimary: true,
    },
    {
        name: "South Africa",
        alpha2Code: "ZA",
        alpha3Code: "ZAF",
        dialingCode: 27,
        dialingCodePrimary: true,
    },
    {
        name: "South Korea",
        alpha2Code: "KR",
        alpha3Code: "KOR",
        dialingCode: 82,
        dialingCodePrimary: true,
    },
    {
        name: "Spain",
        alpha2Code: "ES",
        alpha3Code: "ESP",
        dialingCode: 34,
        dialingCodePrimary: true,
    },
    {
        name: "Sri Lanka",
        alpha2Code: "LK",
        alpha3Code: "LKA",
        dialingCode: 94,
        dialingCodePrimary: true,
    },
    {
        name: "Sudan",
        alpha2Code: "SD",
        alpha3Code: "SDN",
        dialingCode: 249,
        dialingCodePrimary: true,
    },
    {
        name: "Sweden",
        alpha2Code: "SE",
        alpha3Code: "SWE",
        dialingCode: 46,
        dialingCodePrimary: true,
    },
    {
        name: "Switzerland",
        alpha2Code: "CH",
        alpha3Code: "CHE",
        dialingCode: 41,
        dialingCodePrimary: true,
    },
    {
        name: "Syria",
        alpha2Code: "SY",
        alpha3Code: "SYR",
        dialingCode: 963,
        dialingCodePrimary: true,
    },
    {
        name: "Taiwan",
        alpha2Code: "TW",
        alpha3Code: "TWN",
        dialingCode: 886,
        dialingCodePrimary: true,
    },
    {
        name: "Tajikistan",
        alpha2Code: "TJ",
        alpha3Code: "TJK",
        dialingCode: 992,
        dialingCodePrimary: true,
    },
    {
        name: "Tanzania",
        alpha2Code: "TZ",
        alpha3Code: "TZA",
        dialingCode: 255,
        dialingCodePrimary: true,
    },
    {
        name: "Thailand",
        alpha2Code: "TH",
        alpha3Code: "THA",
        dialingCode: 66,
        dialingCodePrimary: true,
    },
    {
        name: "Togo",
        alpha2Code: "TG",
        alpha3Code: "TGO",
        dialingCode: 228,
        dialingCodePrimary: true,
    },
    {
        name: "Tonga",
        alpha2Code: "TO",
        alpha3Code: "TON",
        dialingCode: 676,
        dialingCodePrimary: true,
    },
    {
        name: "Trinidad and Tobago",
        alpha2Code: "TT",
        alpha3Code: "TTO",
        dialingCode: 1,
        dialingCodePrimary: false,
    },
    {
        name: "Tunisia",
        alpha2Code: "TN",
        alpha3Code: "TUN",
        dialingCode: 216,
        dialingCodePrimary: true,
    },
    {
        name: "Turkey",
        alpha2Code: "TR",
        alpha3Code: "TUR",
        dialingCode: 90,
        dialingCodePrimary: true,
    },
    {
        name: "Turkmenistan",
        alpha2Code: "TM",
        alpha3Code: "TKM",
        dialingCode: 993,
        dialingCodePrimary: true,
    },
    {
        name: "Tuvalu",
        alpha2Code: "TV",
        alpha3Code: "TUV",
        dialingCode: 688,
        dialingCodePrimary: true,
    },
    {
        name: "Uganda",
        alpha2Code: "UG",
        alpha3Code: "UGA",
        dialingCode: 256,
        dialingCodePrimary: true,
    },
    {
        name: "Ukraine",
        alpha2Code: "UA",
        alpha3Code: "UKR",
        dialingCode: 380,
        dialingCodePrimary: true,
    },
    {
        name: "United Arab Emirates",
        alpha2Code: "AE",
        alpha3Code: "ARE",
        dialingCode: 971,
        dialingCodePrimary: true,
    },
    {
        name: "United Kingdom",
        alpha2Code: "GB",
        alpha3Code: "GBR",
        dialingCode: 44,
        dialingCodePrimary: true,
    },
    {
        name: "United States",
        alpha2Code: "US",
        alpha3Code: "USA",
        dialingCode: 1,
        dialingCodePrimary: true,
    },
    {
        name: "Uruguay",
        alpha2Code: "UY",
        alpha3Code: "URY",
        dialingCode: 598,
        dialingCodePrimary: true,
    },
    {
        name: "Uzbekistan",
        alpha2Code: "UZ",
        alpha3Code: "UZB",
        dialingCode: 998,
        dialingCodePrimary: true,
    },
    {
        name: "Vanuatu",
        alpha2Code: "VU",
        alpha3Code: "VUT",
        dialingCode: 678,
        dialingCodePrimary: true,
    },
    {
        name: "Vatican City",
        alpha2Code: "VA",
        alpha3Code: "VAT",
        dialingCode: 39,
        dialingCodePrimary: false,
    },
    {
        name: "Venezuela",
        alpha2Code: "VE",
        alpha3Code: "VEN",
        dialingCode: 58,
        dialingCodePrimary: true,
    },
    {
        name: "Vietnam",
        alpha2Code: "VN",
        alpha3Code: "VNM",
        dialingCode: 84,
        dialingCodePrimary: true,
    },
    {
        name: "Yemen",
        alpha2Code: "YE",
        alpha3Code: "YEM",
        dialingCode: 967,
        dialingCodePrimary: true,
    },
    {
        name: "Zambia",
        alpha2Code: "ZM",
        alpha3Code: "ZMB",
        dialingCode: 260,
        dialingCodePrimary: true,
    },
    {
        name: "Zimbabwe",
        alpha2Code: "ZW",
        alpha3Code: "ZWE",
        dialingCode: 263,
        dialingCodePrimary: true,
    },
];
